In [1]:
import pandas as pd
import numpy as np

import random
import string
import os
import boto3
from sqlalchemy import text, create_engine
import requests

from datetime import datetime, timedelta
import random

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

from concurrent.futures import ThreadPoolExecutor, as_completed

import time
import random
from io import BytesIO

In [2]:
def download_and_upload(row, label_directory, batch_id):
    index = row.name  # If using iterrows()
    if not row.image_link.startswith('http'):
        return None

    try:
        # Random sleep between 0.5 and 2.5 seconds
        time.sleep(random.uniform(0.5, 2.5))

        response = requests.get(row.image_link, verify=False, timeout=10)
        if response.status_code == 200:
            file_name = f"{row.asset_id}.jpg"
            file_path = os.path.join(label_directory, file_name)
            
            with open(file_path, 'wb') as f:
                f.write(response.content)

            s3.upload_file(file_path, 'clip-art-monster-images-for-labeling', f"batch_{batch_id}/{file_name}")
            return index
        else:
            print(f"[{index}] Failed: Status code {response.status_code}")
    except Exception as e:
        print(f"[{index}] Exception: {e}")
    return None

db_connection_string = "postgresql+pg8000://clipart_monster_db_user:iV0BUFPv0rMLu5MKVXesLlvFT3E6MneJ@dpg-cocp8eq0si5c73an4rp0-a.ohio-postgres.render.com/clipart_monster_db_prod"
db_connection_string_dev = "postgresql+pg8000://clipart_monster_db_user:iV0BUFPv0rMLu5MKVXesLlvFT3E6MneJ@dpg-cocp8eq0si5c73an4rp0-a.ohio-postgres.render.com/clipart_monster_db"

In [3]:

engine = create_engine(db_connection_string)
engine_dev = create_engine(db_connection_string_dev)

In [ ]:
with engine_dev.connect() as connection_dev:
    label_image_table = pd.read_sql('SELECT * FROM "label_data.selected_assets_new"', connection_dev)

with engine.connect() as connection_prod:
    filtered_assets = pd.read_sql('''
        SELECT a.asset_id, a.image_link
        FROM "content"."assets" a
        JOIN (
            SELECT asset_id FROM "model_predictions"."mono_line_segmentation"
            UNION
            SELECT asset_id FROM "model_predictions"."multi_line_segmentation"
        ) m ON a.asset_id = m.asset_id
        WHERE a.s3 = TRUE
    ''', connection_prod)
image_links = filtered_assets[["asset_id", "image_link"]]

In [ ]:
######################
#increment batch id by 1
batch_id = np.max(label_image_table.batch_id) + 1

######################
#remove already selected assets
is_selected= label_image_table \
    .filter(['asset_id']) \
    .assign(selected = 'yes')

avaiable_assets = filtered_assets \
    .merge(image_links, on = 'asset_id', how = 'left') \
    .merge(is_selected, on = 'asset_id', how = 'left') \
    .query('selected != "yes"')



#set the label directory
label_directory =  'C:/Users/noahs/Documents/labeling/batch_' + str(batch_id) + '/'

os.makedirs(label_directory)

In [6]:
avaiable_assets

,asset_id,image_link_x,image_link_y,selected
0,6411949,https://t3.ftcdn.net/jpg/05/15/18/46/360_F_515...,https://t3.ftcdn.net/jpg/05/15/18/46/360_F_515...,NaN
1,6384334,https://t3.ftcdn.net/jpg/14/51/71/80/360_F_145...,https://t3.ftcdn.net/jpg/14/51/71/80/360_F_145...,NaN
2,724526,https://media.istockphoto.com/id/1193493836/ve...,https://media.istockphoto.com/id/1193493836/ve...,NaN
3,6384442,https://media.istockphoto.com/id/1491204436/ve...,https://media.istockphoto.com/id/1491204436/ve...,NaN
4,6384476,https://media.istockphoto.com/id/1409516093/ve...,https://media.istockphoto.com/id/1409516093/ve...,NaN
...,...,...,...,...
2036480,3888,https://t4.ftcdn.net/jpg/16/49/93/69/360_F_164...,https://t4.ftcdn.net/jpg/16/49/93/69/360_F_164...,NaN
2036481,2552,https://image.shutterstock.com/z/stock-vector-...,https://image.shutterstock.com/z/stock-vector-...,NaN
2036482,2559,https://image.shutterstock.com/z/stock-vector-...,https://image.shutterstock.com/z/stock-vector-...,NaN
2036483,2930,https://t3.ftcdn.net/jpg/14/38/74/06/360_F_143...,https://t3.ftcdn.net/jpg/14/38/74/06/360_F_143...,NaN
2036484,2824,https://t4.ftcdn.net/jpg/14/38/74/05/360_F_143...,https://t4.ftcdn.net/jpg/14/38/74/05/360_F_143...,NaN

In [15]:
######################
#build asset table

date = datetime.now().strftime("%Y-%m-%d")

selected_assets = avaiable_assets \
    .sample(10000) \
    .filter(['asset_id','image_link']) \
    .assign(batch_id = 1) \
    .assign(date_created = date) \
    .assign(label_count = 0) \
    .assign(clip_art_type = 0) \
    .assign(count = 0) \
    .assign(line_width = 0) \
    .assign(color_depth = 0) \
    .assign(primary_color = 0) \
    .reset_index() \
    .drop(['index'],axis = 1)
        

# successful_downloads = []
# with ThreadPoolExecutor(max_workers=20) as executor:
#     futures = [
#         executor.submit(download_and_upload, row, label_directory, batch_id)
#         for _, row in selected_assets.iterrows()
#     ]

#     for i, future in enumerate(as_completed(futures), 1):
#         result = future.result()
#         print(f"{i} out of {len(selected_assets)}")
#         if result is not None:
#             successful_downloads.append(result)
            
# # Filter the DataFrame to keep only the rows with successful downloads
# selected_assets = selected_assets.loc[successful_downloads]

# # Reset the index if needed
# selected_assets = selected_assets.reset_index(drop=True)

temp = selected_assets.copy()

temp['sub_batch'] = ((temp.index // 5) + 1).astype(int)
temp['large_sub_batch'] = ((temp.index // 500) + 1).astype(int)
temp['asset_type'] = 'undetermined'
temp['color_type'] = 'undetermined'
temp['task_type'] = 'line_width_type'
temp['rule_index'] = 1

In [14]:
temp

,asset_id,batch_id,date_created,label_count,clip_art_type,count,line_width,color_depth,primary_color,sub_batch,large_sub_batch,asset_type,color_type,rule_index
0,8816146,1,2026-04-20,0,0,0,0,0,0,1,1,line_width_type,undetermined,1
1,8082934,1,2026-04-20,0,0,0,0,0,0,1,1,line_width_type,undetermined,1
2,4573549,1,2026-04-20,0,0,0,0,0,0,1,1,line_width_type,undetermined,1
3,10958501,1,2026-04-20,0,0,0,0,0,0,1,1,line_width_type,undetermined,1
4,1516105,1,2026-04-20,0,0,0,0,0,0,1,1,line_width_type,undetermined,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,8591082,1,2026-04-20,0,0,0,0,0,0,2000,20,line_width_type,undetermined,1
9996,11191002,1,2026-04-20,0,0,0,0,0,0,2000,20,line_width_type,undetermined,1
9997,1540039,1,2026-04-20,0,0,0,0,0,0,2000,20,line_width_type,undetermined,1
9998,6706503,1,2026-04-20,0,0,0,0,0,0,2000,20,line_width_type,undetermined,1
9999,4411660,1,2026-04-20,0,0,0,0,0,0,2000,20,line_width_type,undetermined,1

In [ ]:
with engine_dev.begin() as conn:  # begin() auto-commits; faster/cleaner than connect() for writes
    temp.to_sql(
        "label_data.selected_assets_new",
        con=conn,
        if_exists="append",
        index=False,
        chunksize=5_000
        )