In [1]:
import pandas as pd
import numpy as np

import random
import string
import os
import boto3
from sqlalchemy import text, create_engine
import requests

from datetime import datetime, timedelta
import random

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

from concurrent.futures import ThreadPoolExecutor, as_completed

import time
import random
from io import BytesIO

In [2]:
def download_and_upload(row, label_directory, batch_id):
    index = row.name  # If using iterrows()
    if not row.image_link.startswith('http'):
        return None

    try:
        # Random sleep between 0.5 and 2.5 seconds
        time.sleep(random.uniform(0.5, 2.5))

        response = requests.get(row.image_link, verify=False, timeout=10)
        if response.status_code == 200:
            file_name = f"{row.asset_id}.jpg"
            file_path = os.path.join(label_directory, file_name)
            
            with open(file_path, 'wb') as f:
                f.write(response.content)

            s3.upload_file(file_path, 'clip-art-monster-images-for-labeling', f"batch_{batch_id}/{file_name}")
            return index
        else:
            print(f"[{index}] Failed: Status code {response.status_code}")
    except Exception as e:
        print(f"[{index}] Exception: {e}")
    return None

db_connection_string = "postgresql+pg8000://clipart_monster_db_user:iV0BUFPv0rMLu5MKVXesLlvFT3E6MneJ@dpg-cocp8eq0si5c73an4rp0-a.ohio-postgres.render.com/clipart_monster_db_prod"
db_connection_string_dev = "postgresql+pg8000://clipart_monster_db_user:iV0BUFPv0rMLu5MKVXesLlvFT3E6MneJ@dpg-cocp8eq0si5c73an4rp0-a.ohio-postgres.render.com/clipart_monster_db"

In [3]:

engine = create_engine(db_connection_string)
engine_dev = create_engine(db_connection_string_dev)

In [4]:
with engine_dev.connect() as connection_dev:
    label_image_table = pd.read_sql('SELECT * FROM "label_data.selected_assets_new"', connection_dev)

with engine.connect() as connection_prod:
    filtered_assets = pd.read_sql('''
        SELECT a.asset_id, a.image_link
        FROM "content"."assets" a
        JOIN (
            SELECT asset_id FROM "model_predictions"."multi_color"
        ) m ON a.asset_id = m.asset_id
        WHERE a.s3 = TRUE
    ''', connection_prod)
image_links = filtered_assets[["asset_id", "image_link"]]

In [ ]:
######################
#increment batch id by 1
batch_id = np.max(label_image_table.batch_id) + 1

######################
#remove already selected assets
is_selected= label_image_table \
    .filter(['asset_id']) \
    .assign(selected = 'yes')

avaiable_assets = filtered_assets \
    .merge(image_links, on = 'asset_id', how = 'left') \
    .merge(is_selected, on = 'asset_id', how = 'left') \
    .query('selected != "yes"')
    .rename(columns={'image_link_x': 'image_link'})




# #set the label directory
# label_directory =  'C:/Users/noahs/Documents/labeling/batch_' + str(batch_id) + '/'

# os.makedirs(label_directory)

In [8]:
avaiable_assets

,asset_id,image_link,image_link_y,selected
0,23,https://t3.ftcdn.net/jpg/13/68/25/18/360_F_136...,https://t3.ftcdn.net/jpg/13/68/25/18/360_F_136...,NaN
1,74,https://t3.ftcdn.net/jpg/00/01/39/38/360_F_139...,https://t3.ftcdn.net/jpg/00/01/39/38/360_F_139...,NaN
2,128,https://media.istockphoto.com/id/2177747751/ve...,https://media.istockphoto.com/id/2177747751/ve...,NaN
3,133,https://media.istockphoto.com/id/1237467812/ve...,https://media.istockphoto.com/id/1237467812/ve...,NaN
4,151,https://media.istockphoto.com/id/1307922143/ve...,https://media.istockphoto.com/id/1307922143/ve...,NaN
...,...,...,...,...
1248998,11266978,https://image.shutterstock.com/z/stock-vector-...,https://image.shutterstock.com/z/stock-vector-...,NaN
1248999,11267000,https://image.shutterstock.com/z/stock-vector-...,https://image.shutterstock.com/z/stock-vector-...,NaN
1249000,11267536,https://img.b2bpic.net/premium-vector/martin-l...,https://img.b2bpic.net/premium-vector/martin-l...,NaN
1249001,11267548,https://img.b2bpic.net/premium-vector/england-...,https://img.b2bpic.net/premium-vector/england-...,NaN
1249002,11267720,https://c7.alamy.com/comp/3D0DFH1/editable-vec...,https://c7.alamy.com/comp/3D0DFH1/editable-vec...,NaN

In [9]:
######################
#build asset table

date = datetime.now().strftime("%Y-%m-%d")

selected_assets = avaiable_assets \
    .rename(columns={'image_link_x': 'image_link'}) \
    .sample(10000) \
    .filter(['asset_id','image_link']) \
    .assign(batch_id = 1) \
    .assign(date_created = date) \
    .assign(label_count = 0) \
    .assign(clip_art_type = 0) \
    .assign(count = 0) \
    .assign(line_width = 0) \
    .assign(color_depth = 0) \
    .assign(primary_color = 0) \
    .reset_index() \
    .drop(['index'],axis = 1)
        

# successful_downloads = []
# with ThreadPoolExecutor(max_workers=20) as executor:
#     futures = [
#         executor.submit(download_and_upload, row, label_directory, batch_id)
#         for _, row in selected_assets.iterrows()
#     ]

#     for i, future in enumerate(as_completed(futures), 1):
#         result = future.result()
#         print(f"{i} out of {len(selected_assets)}")
#         if result is not None:
#             successful_downloads.append(result)
            
# # Filter the DataFrame to keep only the rows with successful downloads
# selected_assets = selected_assets.loc[successful_downloads]

# # Reset the index if needed
# selected_assets = selected_assets.reset_index(drop=True)

temp = selected_assets.copy()

temp['sub_batch'] = ((temp.index // 5) + 1).astype(int)
temp['large_sub_batch'] = ((temp.index // 500) + 1).astype(int)
temp['asset_type'] = 'undetermined'
temp['color_type'] = 'undetermined'
temp['task_type'] = 'color_fill_type'
temp['rule_index'] = 4

In [10]:
temp

,asset_id,image_link,batch_id,date_created,label_count,clip_art_type,count,line_width,color_depth,primary_color,sub_batch,large_sub_batch,asset_type,color_type,task_type,rule_index
0,3021696,https://clipart-library.com/data_images/98848.png,1,2026-05-13,0,0,0,0,0,0,1,1,undetermined,undetermined,color_fill_type,4
1,9815936,https://image.shutterstock.com/z/stock-vector-...,1,2026-05-13,0,0,0,0,0,0,1,1,undetermined,undetermined,color_fill_type,4
2,2961893,https://img.clipart-library.com/2/clip-cleanin...,1,2026-05-13,0,0,0,0,0,0,1,1,undetermined,undetermined,color_fill_type,4
3,7228296,https://image.shutterstock.com/z/stock-vector-...,1,2026-05-13,0,0,0,0,0,0,1,1,undetermined,undetermined,color_fill_type,4
4,4448152,https://clipart.com/thumbs.php?f=/images-clipa...,1,2026-05-13,0,0,0,0,0,0,1,1,undetermined,undetermined,color_fill_type,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1146513,https://media.istockphoto.com/id/181626306/vec...,1,2026-05-13,0,0,0,0,0,0,2000,20,undetermined,undetermined,color_fill_type,4
9996,2107623,https://media.istockphoto.com/id/480677637/vec...,1,2026-05-13,0,0,0,0,0,0,2000,20,undetermined,undetermined,color_fill_type,4
9997,10241228,https://images.rawpixel.com/image_png_800/cHJp...,1,2026-05-13,0,0,0,0,0,0,2000,20,undetermined,undetermined,color_fill_type,4
9998,10874943,https://img.b2bpic.net/premium-psd/regal-carto...,1,2026-05-13,0,0,0,0,0,0,2000,20,undetermined,undetermined,color_fill_type,4
9999,1407875,https://image.shutterstock.com/z/stock-photo-t...,1,2026-05-13,0,0,0,0,0,0,2000,20,undetermined,undetermined,color_fill_type,4

In [11]:
chunksize = 65535 // len(temp.columns)

temp.to_sql(
    "label_data.selected_assets_new",
    con=engine_dev,
    if_exists="append",
    index=False,
    method="multi",
    chunksize=chunksize
)

10000

In [25]:
import pandas as pd
import numpy as np
import time

from sqlalchemy import create_engine, text

DB_CONNECTION_PROD = "postgresql+pg8000://clipart_monster_db_user:iV0BUFPv0rMLu5MKVXesLlvFT3E6MneJ@dpg-cocp8eq0si5c73an4rp0-a.ohio-postgres.render.com/clipart_monster_db_prod"
DB_CONNECTION_DEV = "postgresql+pg8000://clipart_monster_db_user:iV0BUFPv0rMLu5MKVXesLlvFT3E6MneJ@dpg-cocp8eq0si5c73an4rp0-a.ohio-postgres.render.com/clipart_monster_db"

engine = create_engine(DB_CONNECTION_PROD)
engine_dev = create_engine(DB_CONNECTION_DEV)

connection = engine.connect()
connection_dev = engine_dev.connect()

In [36]:
with engine.connect() as connection_prod:
    photos = pd.read_sql("SELECT * FROM model_predictions.rule_labels where model_version = 'A1_0.09' and probability > .94", connection_prod)

In [48]:
query = """
SELECT * FROM "label_data.selected_assets_new" where task_type != 'asset_type'
"""

with engine_dev.connect() as connection_dev:
    selected_assets = pd.read_sql(query, connection_dev)

ids_to_delete = selected_assets.merge(photos, on = 'asset_id', how = 'inner')['asset_id'].tolist()

In [49]:
ids_to_delete

[]

In [47]:
query = """
SELECT * FROM "label_data.selected_assets_new" where task_type != 'asset_type'
"""

with engine_dev.connect() as connection_dev:
    selected_assets = pd.read_sql(query, connection_dev)

ids_to_delete = selected_assets.merge(photos, on = 'asset_id', how = 'inner')['asset_id'].tolist()

placeholders = ', '.join([f':id{i}' for i in range(len(ids_to_delete))])
query = text(f"""DELETE FROM "label_data.selected_assets_new" WHERE asset_id IN ({placeholders})""")
params = {f'id{i}': v for i, v in enumerate(ids_to_delete)}

with engine_dev.connect() as connection_dev:
    connection_dev.execute(query, params)
    connection_dev.commit()

In [51]:
query = """
SELECT * FROM "label_data.prompt_responses" where task_type != 'asset_type'
"""

with engine_dev.connect() as connection_dev:
    selected_assets = pd.read_sql(query, connection_dev)

ids_to_delete = selected_assets.merge(photos, on = 'asset_id', how = 'inner')['asset_id'].tolist()

In [52]:
ids_to_delete

[]

In [50]:
query = """
SELECT * FROM "label_data.prompt_responses" where task_type != 'asset_type'
"""

with engine_dev.connect() as connection_dev:
    selected_assets = pd.read_sql(query, connection_dev)

ids_to_delete = selected_assets.merge(photos, on = 'asset_id', how = 'inner')['asset_id'].tolist()

placeholders = ', '.join([f':id{i}' for i in range(len(ids_to_delete))])
query = text(f"""DELETE FROM "label_data.prompt_responses" WHERE asset_id IN ({placeholders}) and task_type != 'asset_type'""")
params = {f'id{i}': v for i, v in enumerate(ids_to_delete)}

with engine_dev.connect() as connection_dev:
    connection_dev.execute(query, params)
    connection_dev.commit()

In [37]:
query = """
SELECT * FROM "label_data.prompt_responses" where task_type != 'asset_type'
"""

with engine_dev.connect() as connection_dev:
    prompt_responses = pd.read_sql(query, connection_dev)

In [40]:
prompt_responses.merge(photos, on = 'asset_id', how = 'inner')

,datetime_created,asset_id,labeler_source,labeler_id,labeler_count,task_type_x,rule_index_x,prompt_response,id,task_type_y,rule_index_y,probability,label,model_version,created_at
0,2025-01-22 17:16:18.020075,641255,Internal,Steve,2,clip_art_type,6,no,5299,asset_type,1,0.983873,1,A1_0.09,2026-04-06
1,2025-01-03 18:57:06.656001,712544,Internal,Steve,1,clip_art_type,1,no,5377,asset_type,1,0.985326,1,A1_0.09,2026-04-06
2,2025-01-03 19:02:00.570005,635034,Internal,Steve,2,clip_art_type,1,no,5378,asset_type,1,0.992680,1,A1_0.09,2026-04-06
3,2025-01-03 19:05:11.937417,632305,Internal,Steve,2,clip_art_type,1,no,5471,asset_type,1,0.993422,1,A1_0.09,2026-04-06
4,2025-01-22 17:16:51.642474,758183,Internal,Steve,2,clip_art_type,6,no,5642,asset_type,1,0.987825,1,A1_0.09,2026-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7906,2026-04-20 20:31:01.065656,1059198,Internal,Noah,2,color_fill_type,1,no,693823,asset_type,1,0.987590,1,A1_0.09,2026-04-06
7907,2026-04-20 20:31:02.713691,9987318,Internal,Noah,2,color_fill_type,1,no,693825,asset_type,1,0.995196,1,A1_0.09,2026-04-06
7908,2026-04-20 20:31:07.424643,8826399,Internal,Noah,2,color_fill_type,1,no,693829,asset_type,1,0.955956,1,A1_0.09,2026-04-06
7909,2026-04-20 20:31:20.783766,7365327,Internal,Noah,2,color_fill_type,1,no,693834,asset_type,1,0.985468,1,A1_0.09,2026-04-06
7910,2026-04-20 20:31:21.512063,10087663,Internal,Noah,2,color_fill_type,1,no,693835,asset_type,1,0.986791,1,A1_0.09,2026-04-06