In [1]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine, text

DB_CONNECTION_PROD = "postgresql+pg8000://clipart_monster_db_user:iV0BUFPv0rMLu5MKVXesLlvFT3E6MneJ@dpg-cocp8eq0si5c73an4rp0-a.ohio-postgres.render.com/clipart_monster_db_prod"
DB_CONNECTION_DEV = "postgresql+pg8000://clipart_monster_db_user:iV0BUFPv0rMLu5MKVXesLlvFT3E6MneJ@dpg-cocp8eq0si5c73an4rp0-a.ohio-postgres.render.com/clipart_monster_db"

engine = create_engine(DB_CONNECTION_PROD)
engine_dev = create_engine(DB_CONNECTION_DEV)

connection = engine.connect()
connection_dev = engine_dev.connect()

prompt_data = pd.read_sql('SELECT * FROM "label_data.prompt_responses"', connection_dev)

current_data = pd.read_sql(
    'SELECT * FROM "label_data.asset_type.rule.labels"', connection_dev
)

In [2]:
label_set = (
    prompt_data.assign(
        yes_response=lambda x: np.where(x.prompt_response == "yes", 1, 0)
    )
    .groupby(["asset_id", "task_type", "rule_index"])
    .agg(agree_count=("yes_response", "sum"), samples=("asset_id", "count"))
    .query("samples > 1")
    .assign(percent_agree=lambda x: x.agree_count / x.samples)
    .query("percent_agree != .5")
    .assign(label=lambda x: np.where(x.percent_agree < 0.5, 0, 1))
    .filter(["asset_id", "label", "percent_agree"])
    .assign(label_strength="weak")
    .assign(
        label_strength=lambda x: np.where(
            (x.percent_agree == 0) | (x.percent_agree == 1), "strong", x.label_strength
        )
    )
    .assign(label_source="Internal")
    .reset_index()
)

In [14]:
prompt_data.assign( \
        yes_response=lambda x: np.where(x.prompt_response == "yes", 1, 0)) \
    .groupby(["asset_id", "task_type", "rule_index"]) \
    .agg(agree_count=("yes_response", "sum"), samples=("asset_id", "count")) \
    .query("samples > 1") \
    .assign(percent_agree=lambda x: x.agree_count / x.samples) \
    .query("percent_agree != .5") \
    .assign(label=lambda x: np.where(x.percent_agree < 0.5, 0, 1))

                                agree_count  samples  percent_agree  label
asset_id task_type  rule_index
435      asset_type 1                     1        3       0.333333      0
                    2                     1        3       0.333333      0
                    3                     2        3       0.666667      1
                    5                     2        2       1.000000      1
                    6                     2        2       1.000000      1
...                                     ...      ...            ...    ...
11260218 same_style 1                     2        2       1.000000      1
11260229 asset_type 7                     0        2       0.000000      0
11263903 asset_type 7                     0        2       0.000000      0
11264001 asset_type 7                     0        2       0.000000      0
11264012 asset_type 7                     0        2       0.000000      0

[316083 rows x 4 columns]

In [3]:
label_set

,asset_id,task_type,rule_index,label,percent_agree,label_strength,label_source
0,435,asset_type,1,0,0.333333,weak,Internal
1,435,asset_type,2,0,0.333333,weak,Internal
2,435,asset_type,3,1,0.666667,weak,Internal
3,435,asset_type,5,1,1.000000,strong,Internal
4,435,asset_type,6,1,1.000000,strong,Internal
...,...,...,...,...,...,...,...
316078,11260218,same_style,1,1,1.000000,strong,Internal
316079,11260229,asset_type,7,0,0.000000,strong,Internal
316080,11263903,asset_type,7,0,0.000000,strong,Internal
316081,11264001,asset_type,7,0,0.000000,strong,Internal
316082,11264012,asset_type,7,0,0.000000,strong,Internal